CREATE TABLE ACCEPT_M_REQUEST (
  `ACCEPT_ID` INT NOT NULL,
  `REQUEST_ID` INT NOT NULL,
  `C_ROOM_ID` INT NOT NULL,
  `POST_ID` INT NOT NULL,
  `USER_ID2` INT NOT NULL,
  `IS_ACCEPTED` BOOLEAN NOT NULL,
  `A_USER_ID` VARCHAR(255) NOT NULL,
  `CREAT_AT` TIMESTAMP NOT NULL,
  PRIMARY KEY (ACCEPT_ID, REQUEST_ID, C_ROOM_ID, POST_ID, USER_ID2),
  CONSTRAINT `FK_MATCHING_REQUEST_TO_ACCEPT_M_REQUEST_1` FOREIGN KEY (`REQUEST_ID`) REFERENCES `MATCHING_REQUEST` (`REQUEST_ID`),
  CONSTRAINT `FK_MATCHING_REQUEST_TO_ACCEPT_M_REQUEST_2` FOREIGN KEY (`C_ROOM_ID`) REFERENCES `MATCHING_REQUEST` (`C_ROOM_ID`),
  CONSTRAINT `FK_MATCHING_REQUEST_TO_ACCEPT_M_REQUEST_3` FOREIGN KEY (`POST_ID`) REFERENCES `MATCHING_REQUEST` (`POST_ID`),
  CONSTRAINT `FK_MATCHING_REQUEST_TO_ACCEPT_M_REQUEST_4` FOREIGN KEY (`USER_ID2`) REFERENCES `MATCHING_REQUEST` (`USER_ID`)
);

CREATE TABLE MATCHING_REQUEST (
  `REQUEST_ID` INT NOT NULL,
  `C_ROOM_ID` INT NOT NULL,
  `POST_ID` INT NOT NULL,
  `USER_ID` INT NOT NULL,
  `IS_REQUSTED` BOOLEAN NOT NULL,
  `CREAT_AT` TIMESTAMP NOT NULL,
  PRIMARY KEY (`REQUEST_ID`, `C_ROOM_ID`, `POST_ID`, `USER_ID`),
  CONSTRAINT `FK_CHAT_ROOM_TO_MATCHING_REQUEST_1` FOREIGN KEY (`C_ROOM_ID`) REFERENCES `CHAT_ROOM` (`C_ROOM_ID`),
  CONSTRAINT `FK_CHAT_ROOM_TO_MATCHING_REQUEST_2` FOREIGN KEY (`POST_ID`) REFERENCES `CHAT_ROOM` (`POST_ID`),
  CONSTRAINT `FK_CHAT_ROOM_TO_MATCHING_REQUEST_3` FOREIGN KEY (`USER_ID`) REFERENCES `CHAT_ROOM` (`USER_ID`)
);

CREATE TABLE USER (
  `USER_ID` INT NOT NULL,
  `USER_PW` VARCHAR(30) NOT NULL,
  `PHONE_NUM` VARCHAR(255) NOT NULL,
  `NICK_NAME` VARCHAR(255) NOT NULL,
  `PROFILE_PIC` VARCHAR(255) NULL,
  `USER_TYPE` TINYINT(2) NOT NULL COMMENT '11: 관리자, 10: 비지니스 사용자, 1: 일반회원, 0: 탈퇴',
  `CREAT_AT` TIMESTAMP NOT NULL COMMENT 'YYYY-MM-DD HH:MM:SS 형식',
  `IS_DELETRD` BOOLEAN NOT NULL,
  PRIMARY KEY (USER_ID)
);

CREATE TABLE POST (
  `POST_ID` INT NOT NULL,
  `USER_ID` INT NOT NULL,
  `DIAS_NAME` VARCHAR(255) NOT NULL,
  `DIAS_TYPE` VARCHAR(255) NOT NULL,
  `DIAS_ADDRESS` VARCHAR(255) NOT NULL,
  `WANTED_ST_DATE` DATE NOT NULL,
  `WANTED_E_DATE` DATE NOT NULL,
  `POST_DETAIL` TEXT NULL,
  `CREAT_AT` TIMESTAMP NOT NULL,
  `IS_DELETED` BOOLEAN NOT NULL,
  `LAST_CREAT_AT` VARCHAR(255) NULL,
  `Field2` VARCHAR(255) NULL,
  `Field3` VARCHAR(255) NULL,
  `Field4` VARCHAR(255) NULL,
  PRIMARY KEY (POST_ID, USER_ID),
  CONSTRAINT FK_USER_TO_POST_1 FOREIGN KEY (USER_ID) REFERENCES `USER` (USER_ID)
);

CREATE TABLE MESSAGE (
  `CHAT_MSG_ID` INT NOT NULL,
  `C_ROOM_ID` INT NOT NULL,
  `POST_ID` INT NOT NULL,
  `USER_ID` INT NOT NULL,
  `SEND_MSG` TEXT NOT NULL,
  `CREAT_AT` TIMESTAMP NOT NULL,
  PRIMARY KEY (`CHAT_MSG_ID`, `C_ROOM_ID`, `POST_ID`, `USER_ID`),
  CONSTRAINT `FK_CHAT_ROOM_TO_MESSAGE_1` FOREIGN KEY (`C_ROOM_ID`) REFERENCES `CHAT_ROOM` (`C_ROOM_ID`),
  CONSTRAINT `FK_CHAT_ROOM_TO_MESSAGE_2` FOREIGN KEY (`POST_ID`) REFERENCES `CHAT_ROOM` (`POST_ID`),
  CONSTRAINT `FK_CHAT_ROOM_TO_MESSAGE_3` FOREIGN KEY (`USER_ID`) REFERENCES `CHAT_ROOM` (`USER_ID`)
);

CREATE TABLE LOCATION (
  `LOCATION_ID` INT NOT NULL,
  `LOCATION_NAME` VARCHAR(255) NOT NULL,
  `LOCATION_TEXT` TEXT NOT NULL,
  `WAITING_AMOUNT` INT NOT NULL,
  PRIMARY KEY (`LOCATION_ID`)
);

CREATE TABLE CHAT_ROOM (
  `C_ROOM_ID` INT NOT NULL,
  `POST_ID` INT NOT NULL,
  `USER_ID` INT NOT NULL,
  `SENDER_ID` VARCHAR(255) NOT NULL,
  `CREAT_AT` TIMESTAMP NOT NULL,
  PRIMARY KEY (C_ROOM_ID, POST_ID, USER_ID),
  CONSTRAINT FK_POST_TO_CHAT_ROOM_1 FOREIGN KEY (POST_ID) REFERENCES `POST` (`POST_ID`),
  CONSTRAINT FK_POST_TO_CHAT_ROOM_2 FOREIGN KEY (USER_ID) REFERENCES `POST` (`USER_ID`)
);
